# Generated by Django 5.1.6 on 2025-04-05 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dasha', '0002_dashaeffect'),
    ]

    operations = [
        migrations.CreateModel(
            name='KundliMatching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varna_score', models.IntegerField()),
                ('vasha_score', models.IntegerField()),
                ('tara_score', models.IntegerField()),
                ('yoni_score', models.IntegerField()),
                ('graha_maitry_score', models.IntegerField()),
                ('gana_score', models.IntegerField()),
                ('bhakoot_score', models.IntegerField()),
                ('nadi_score', models.IntegerField()),
                ('boy_birth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_boy', to='dasha.birthdetails')),
                ('girl_birth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_girl', to='dasha.birthdetails')),
            ],
        ),
    ]
