# Generated by Django 5.1.6 on 2025-04-02 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BirthDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
                ('birth_time', models.TimeField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('birth_date', 'birth_time', 'latitude', 'longitude')},
            },
        ),
        migrations.CreateModel(
            name='AntarDasha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nakshatra', models.CharField(max_length=50)),
                ('major_dasha', models.CharField(max_length=50)),
                ('remaining_years', models.FloatField()),
                ('antar_dasha_planet', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('birth_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dasha.birthdetails')),
            ],
        ),
        migrations.CreateModel(
            name='MoonPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moon_longitude', models.FloatField()),
                ('nakshatra', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('birth_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dasha.birthdetails')),
            ],
        ),
        migrations.CreateModel(
            name='PlanetaryPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planet', models.CharField(max_length=50)),
                ('speed', models.DecimalField(decimal_places=4, max_digits=8)),
                ('nakshatra', models.CharField(max_length=50)),
                ('rashi', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('birth_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dasha.birthdetails')),
            ],
            options={
                'unique_together': {('birth_details', 'planet')},
            },
        ),
    ]
