# Generated by Django 5.1.6 on 2025-04-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasha', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashaEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahadasha_planet', models.CharField(max_length=50)),
                ('antar_dasha_planet', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('mahadasha_effect', models.TextField()),
                ('antardasha_effect', models.TextField()),
                ('combined_effect', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
