# Generated by Django 5.1.6 on 2025-04-05 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasha', '0002_dashaeffect'),
        ('kundli', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KundliReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ascendant', models.CharField(max_length=50)),
                ('asc_deg', models.FloatField(max_length=20)),
                ('asc_sign', models.CharField(max_length=50)),
                ('birth_sign', models.CharField(max_length=50)),
                ('lagna_chart', models.JSONField()),
                ('houses', models.JSONField()),
                ('planet_positions', models.JSONField()),
                ('planets_longitudes', models.JSONField()),
                ('planet_house_map', models.JSONField()),
                ('sade_sati_result', models.BooleanField()),
                ('sade_sati_phases', models.JSONField()),
                ('manglik_dosha', models.BooleanField()),
                ('kaal_sarp_dosha', models.BooleanField()),
                ('mahapurush_yogas', models.JSONField()),
                ('gaja_kesari_yoga', models.BooleanField()),
                ('budha_aditya_yoga', models.BooleanField()),
                ('pitra_dosha', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('birth_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dasha.birthdetails')),
            ],
        ),
    ]
