# Generated by Django 5.1.6 on 2025-04-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kundli', '0002_kundlireport'),
    ]

    operations = [
        migrations.AddField(
            model_name='kundlireport',
            name='kundli_data',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kundlireport',
            name='pitra_dosha',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='kundlireport',
            name='sade_sati_result',
            field=models.JSONField(),
        ),
    ]
