# Generated by Django 5.1.6 on 2025-04-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kundli', '0004_alter_location_latitude_alter_location_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='kundlireport',
            name='chart_url',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='kundlireport',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kundlireport',
            name='place',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
