# Generated by Django 5.1.6 on 2025-04-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kundli', '0005_kundlireport_chart_url_kundlireport_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kundlireport',
            name='ganra',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='kundlireport',
            name='nadi',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='kundlireport',
            name='nakshatra',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='kundlireport',
            name='varna',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='kundlireport',
            name='yoni',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
