POST https://astro.local/api/1.0/notes/process_note/
Authorization: Token 4519bc0fe68eb280c0d18223ba3c746812e6db22
Content-Type: multipart/form-data; boundary=boundary123
X-App-Source: smartnotes

--boundary123
Content-Disposition: form-data; name="type"

text
--boundary123
Content-Disposition: form-data; name="title"

Testing Note
--boundary123
Content-Disposition: form-data; name="content"

Testing Note Description
--boundary123--

####

GET https://astro.local/api/1.0/notes/process_note/
Authorization: Token 9c17b39de50fd0c83c868d452b432216b8cad08b
Content-Type: multipart/form-data; boundary=boundary123
X-App-Source: smartnotes



####
DELETE  https://astro.local/api/1.0/notes/test/
Authorization: Token 9c17b39de50fd0c83c868d452b432216b8cad08b
Content-Type: multipart/form-data; boundary=boundary123
X-App-Source: smartnotes


####
GET https://astro.local/api/1.0/notes/process_note/
Authorization: Token 4519bc0fe68eb280c0d18223ba3c746812e6db22
Content-Type: multipart/form-data; boundary=boundary123
X-App-Source: smartnotes


####
GET https://83fa6ec71af5.ngrok-free.app/api/1.0/home/wallet/1/transactions/?page=1
Authorization: Token 9c17b39de50fd0c83c868d452b432216b8cad08b
Content-Type: multipart/form-data; boundary=boundary123
X-App-Source: smartnotes


###
PUT https://astro.local/api/1.0/notes/this-is-new-note/
Authorization: Token 9c17b39de50fd0c83c868d452b432216b8cad08b
Content-Type: multipart/form-data; boundary=boundary123
X-App-Source: smartnotes

--boundary123
Content-Disposition: form-data; name="type"

text
--boundary123
Content-Disposition: form-data; name="title"

Testing Note
--boundary123
Content-Disposition: form-data; name="content"

Testing Note Description
--boundary123--



####
GET https://astro.local/api/1.0/notifications/
Authorization: Token 9c17b39de50fd0c83c868d452b432216b8cad08b
Content-Type: multipart/form-data; boundary=boundary123
X-App-Source: smartnotes



####
POST https://astro.local/api/1.0/home/contact/create/
Content-Type: multipart/form-data; boundary=boundary123
Authorization: Token 4519bc0fe68eb280c0d18223ba3c746812e6db22
X-App-Source: smartnotes

--boundary123
Content-Disposition: form-data; name="full_name"

John Doe
--boundary123
Content-Disposition: form-data; name="email"

john.doe@example.com
--boundary123
Content-Disposition: form-data; name="message"

This is my contact query message
--boundary123--

####
