# Generated by Django 5.1.6 on 2025-07-19 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('astrology', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='astrology.blogcomment'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='astrology.blogcategory'),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='astrology.blogpost'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='chat_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='astrology.chatroom'),
        ),
        migrations.AddField(
            model_name='kundlimatching',
            name='boy_birth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_boy', to='astrology.birthdetails'),
        ),
        migrations.AddField(
            model_name='kundlimatching',
            name='girl_birth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_girl', to='astrology.birthdetails'),
        ),
        migrations.AddField(
            model_name='kundlireport',
            name='birth_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astrology.birthdetails'),
        ),
        migrations.AddField(
            model_name='kundlireport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='chat_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='astrology.chatroom'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moonposition',
            name='birth_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astrology.birthdetails'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planetaryposition',
            name='birth_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astrology.birthdetails'),
        ),
        migrations.AddField(
            model_name='userpanchang',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_chats', to='astrology.vendor'),
        ),
        migrations.AddField(
            model_name='vendoravailability',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='astrology.vendor'),
        ),
        migrations.AddField(
            model_name='vendorpaymenthistroy',
            name='chat_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='astrology.chatroom'),
        ),
        migrations.AddField(
            model_name='vendorpaymenthistroy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_payment_histories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorpaymenthistroy',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_payments', to='astrology.vendor'),
        ),
        migrations.AddField(
            model_name='videocall',
            name='chat_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_calls', to='astrology.chatroom'),
        ),
        migrations.AddField(
            model_name='videocall',
            name='initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_calls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='planetaryposition',
            unique_together={('birth_details', 'planet')},
        ),
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('user', 'vendor', 'start_time')},
        ),
        migrations.AlterUniqueTogether(
            name='vendoravailability',
            unique_together={('vendor', 'day_of_week', 'start_time')},
        ),
    ]
