# Generated by Django 5.1.6 on 2025-08-08 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
