# Generated by Django 5.1.6 on 2025-03-30 07:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Panchang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tithi', models.CharField(max_length=50)),
                ('vara', models.CharField(max_length=50)),
                ('nakshatra', models.CharField(max_length=50)),
                ('yoga', models.CharField(max_length=50)),
                ('karana', models.CharField(max_length=50)),
                ('sunrise', models.TimeField()),
                ('sunset', models.TimeField()),
                ('rahu_kaal', models.CharField(max_length=50)),
                ('gulika_kaal', models.CharField(max_length=50)),
                ('yamaganda', models.CharField(max_length=50)),
                ('abhijit_muhurat', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPanchang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Field must contain only alphabetic characters.', regex='^[a-zA-Z]*$')])),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Field must contain only alphabetic characters.', regex='^[a-zA-Z]*$')])),
                ('date_of_birth', models.DateField()),
                ('time_of_birth', models.TimeField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('tithi', models.CharField(max_length=50)),
                ('nakshatra', models.CharField(max_length=50)),
                ('yoga', models.CharField(max_length=50)),
                ('karana', models.CharField(max_length=50)),
                ('vara', models.CharField(max_length=50)),
                ('sunrise', models.TimeField()),
                ('sunset', models.TimeField()),
                ('rahu_kaal', models.CharField(max_length=50)),
                ('gulika_kaal', models.CharField(max_length=50)),
                ('yamaganda', models.CharField(max_length=50)),
                ('abhijit_muhurat', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
