# Generated by Django 5.1.6 on 2025-04-28 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panchang', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpanchang',
            old_name='place_of_birth',
            new_name='place',
        ),
    ]
