# Generated by Django 5.1.6 on 2025-04-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_plan_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='plan',
        ),
        migrations.AddField(
            model_name='plan',
            name='features',
            field=models.ManyToManyField(related_name='features', to='subscription.feature'),
        ),
    ]
