# Generated by Django 5.1.6 on 2025-04-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_remove_feature_plan_plan_features'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfeatureusage',
            old_name='used_quantity',
            new_name='remain_quantity',
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='invoice_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
