# Generated by Django 5.1.6 on 2025-04-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_rename_used_quantity_userfeatureusage_remain_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeatureusage',
            name='remain_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
