# Generated by Django 5.1.6 on 2025-08-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartnotes', '0002_note_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
