# Generated by Django 5.1.6 on 2025-03-20 16:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Field must contain only alphabetic characters.', regex='^[a-zA-Z]*$')])),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Field must contain only alphabetic characters.', regex='^[a-zA-Z]*$')])),
                ('email', models.EmailField(error_messages={'unquie': 'A user with this email already exists.'}, max_length=254, unique=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_user', models.BooleanField(default=True)),
                ('is_accepted_terms', models.BooleanField(default=False)),
                ('country_code', models.CharField(blank=True, max_length=3, null=True)),
                ('cell', models.CharField(blank=True, max_length=12, null=True)),
                ('is_cell_verified', models.BooleanField(default=False)),
                ('social_id', models.CharField(blank=True, max_length=255, null=True)),
                ('provider', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_picture', models.URLField(blank=True, null=True)),
                ('birth_time', models.TimeField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('language_preference', models.CharField(default='English', max_length=10)),
                ('notification_preference', models.BooleanField(default=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=20, null=True)),
                ('is_temporarily_disabled', models.BooleanField(blank=True, default=False, null=True)),
                ('is_parament_disabled', models.BooleanField(blank=True, default=False, null=True)),
                ('is_remember_me', models.BooleanField(blank=True, default=False, null=True)),
                ('password_reset_token', models.TextField(blank=True, null=True)),
                ('is_profile_block', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=100)),
                ('data', models.JSONField(blank=True, default=dict, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('action_date_time', models.DateTimeField()),
                ('browser', models.CharField(blank=True, max_length=100, null=True)),
                ('browser_version', models.CharField(blank=True, max_length=100, null=True)),
                ('os', models.CharField(blank=True, max_length=100, null=True)),
                ('os_version', models.CharField(blank=True, max_length=100, null=True)),
                ('device_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('device_model', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
