# Generated by Django 5.1.6 on 2025-03-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='zodiac_sign',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
