# Generated by Django 5.1.6 on 2025-04-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_zodiac_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='action_date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
