# Generated by Django 5.1.6 on 2025-04-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_customuser_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('otp_created_at', models.DateTimeField()),
                ('attempts', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='TwoFactorEmailDevice',
        ),
    ]
