# Generated by Django 5.1.6 on 2025-04-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_emailotp_delete_twofactoremaildevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='time_format',
            field=models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
