# Generated by Django 5.1.6 on 2025-04-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_customuser_time_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='device_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
