menu_options = [
    {
        "title": "🕉️ Generate Kundli",
        "description": "Create your detailed Kundli and explore your life's path using Vedic astrology. Discover insights about your career, love life, health, and more.",
        "button_text": "Generate Now",
        "image": "static/images/kundli-generate.png",
        "url": "kundli.index",
    },
    {
        "title": "🕉️ Premium Kundli Report",
        "description": "Unlock a personalized and in-depth Premium Kundli analysis. Receive detailed predictions across all areas of life based on advanced Vedic astrology.",
        "button_text": "View Premium Report",
        "image": "static/images/kundli-generate.png",
        "url": "kundli.premium_anaysis",
    },
    {
        "title": "🔮 Kundli Matching",
        "description": "Match Kundlis for marriage compatibility and long-term harmony. Understand relationship potential through traditional Vedic methods.",
        "button_text": "Match Kundlis",
        "image": "static/images/kundi-matching.png",
        "url": "matching.index",
    },
    {
        "title": "🕰️ Dasha & Antardasha",
        "description": "Explore your life’s major and minor planetary periods. Understand how Dashas influence your destiny with accurate Vedic insights.",
        "button_text": "Explore Dasha Periods",
        "image": "static/images/dasha-and-antardasha.png",
        "url": "dasha.index",
    },
    {
        "title": "📅 Panchang Predictions",
        "description": "Access your personalized Panchang for the day. Align your actions with favorable planetary timings to maximize success and harmony.",
        "button_text": "Check Today’s Panchang",
        "image": "static/images/panchang-predition.png",
        "url": "panchang.user_personalized_panchang",
    },
    {
        "title": "🌞 Daily Horoscope",
        "description": "Get your daily astrology forecast and stay prepared. Receive accurate insights into your love life, career, and well-being.",
        "button_text": "Read Today’s Horoscope",
        "image": "static/images/daily-and-weekly-horoscope.png",
        "url": "horoscope.daily_horoscope",
    },
    {
        "title": "📆 Weekly Horoscope",
        "description": "Plan your week ahead with confidence. Receive personalized weekly horoscope insights to guide your decisions and actions.",
        "button_text": "Read Weekly Horoscope",
        "image": "static/images/daily-and-weekly-horoscope.png",
        "url": "horoscope.weekly_horoscope",
    },
    {
        "title": "🔲 Lo Shu Grid Analysis",
        "description": "Understand your core strengths and challenges through the ancient Lo Shu Grid numerology. Align your energies for growth and success.",
        "button_text": "Analyze Your Grid",
        "image": "static/images/lo-shu-grid.png",
        "url": "loshugrid.index",
    },
    {
        "title": "🔢 Name Number Analysis",
        "description": "Discover the numerological vibration of your name. Reveal how it influences your personality, success, and life path.",
        "button_text": "Find Your Name Number",
        "image": "static/images/name-numerology.png",
        "url": "numerology.name_number.index",
    },
    {
        "title": "🔢 Life Path Number",
        "description": "Reveal your true purpose and destiny through your Life Path Number. A must-have guide for personal and spiritual growth.",
        "button_text": "Calculate Life Path",
        "image": "static/images/name-numerology.png",
        "url": "numerology.life_path_number.index",
    },
    {
        "title": "🔢 Destiny Number",
        "description": "Uncover your destined direction and innate strengths with your Destiny Number. Make confident, informed life choices.",
        "button_text": "Reveal Destiny Number",
        "image": "static/images/name-numerology.png",
        "url": "numerology.destiny_number.index",
    },
    {
        "title": "🔢 Personality Number",
        "description": "Discover the personality traits that define how the world sees you. Use your Personality Number to improve self-awareness.",
        "button_text": "Know Your Personality",
        "image": "static/images/name-numerology.png",
        "url": "numerology.personality_number.index",
    },
    {
        "title": "🚗 Driver & Conductor Numbers",
        "description": "Your Driver and Conductor Numbers reveal your inner potential and external journey. Align them for balance and success.",
        "button_text": "Check Your Numbers",
        "image": "static/images/name-numerology.png",
        "url": "numerology.driver_conductor.index",
    },
    {
        "title": "👼 Angel Number Insights",
        "description": "Decode messages from the universe through Angel Numbers. Discover their meanings and their divine guidance for your life.",
        "button_text": "View Angel Number",
        "image": "static/images/name-numerology.png",
        "url": "numerology.angel_number.index",
    },
]
