# Generated by Django 5.1.6 on 2025-04-02 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horoscope', '0002_userhoroscope'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserHoroscope',
        ),
    ]
